"""tambah_tabel_baru

Revision ID: 25318d8fad4e
Revises: 55fa0e4438ad
Create Date: 2026-06-15 20:42:28.010151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '25318d8fad4e'
down_revision: Union[str, Sequence[str], None] = '55fa0e4438ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_zona', sa.String(length=50), nullable=False),
    sa.Column('deskripsi', sa.String(length=255), nullable=True),
    sa.Column('batas_bawah', sa.Float(), nullable=True),
    sa.Column('batas_atas', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_id'), 'zones', ['id'], unique=False)
    op.create_table('pump_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('status_pompa', sa.String(length=10), nullable=True),
    sa.Column('dipicu_oleh', sa.String(length=50), nullable=True),
    sa.Column('waktu_kejadian', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pump_logs_id'), 'pump_logs', ['id'], unique=False)
    op.create_table('sensor_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('kelembapan_tanah', sa.Float(), nullable=False),
    sa.Column('suhu_udara', sa.Float(), nullable=True),
    sa.Column('kelembapan_udara', sa.Float(), nullable=True),
    sa.Column('ph_tanah', sa.Float(), nullable=True),
    sa.Column('intensitas_cahaya', sa.Integer(), nullable=True),
    sa.Column('status_hujan', sa.Boolean(), nullable=True),
    sa.Column('debit_air', sa.Float(), nullable=True),
    sa.Column('waktu_rekam', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_data_id'), 'sensor_data', ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_data_id'), table_name='sensor_data')
    op.drop_table('sensor_data')
    op.drop_index(op.f('ix_pump_logs_id'), table_name='pump_logs')
    op.drop_table('pump_logs')
    op.drop_index(op.f('ix_zones_id'), table_name='zones')
    op.drop_table('zones')
    # ### end Alembic commands ###
